local g = vim.g
g.netrw_special_syntax=true
vim.cmd [[ hi netrwDoc term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwPix term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwCompress term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwData term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwTilde term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwHdr term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwLex term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwLib term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwYacc term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwObj term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwTmp term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwTags term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwSymLink term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]
vim.cmd [[ hi netrwMakefile term=NONE cterm=NONE gui=NONE ctermfg=420 ctermbg=47 guifg=Gray ]]

vim.cmd [[ syn match netrwMyCustomJS "\(\S\+ \)*\S\+\.\%(js\)\>" contains=netrwTreeBar,@NoSpell ]]
vim.cmd [[ syn match netrwMyCustomTS "\(\S\+ \)*\S\+\.\%(ts\)\>" contains=netrwTreeBar,@NoSpell ]]
vim.cmd [[ syn match netrwMyCustomPHP "\(\S\+ \)*\S\+\.\%(php\)\>" contains=netrwTreeBar,@NoSpell ]]
vim.cmd [[ syn match netrwMyCustomJSON "\(\S\+ \)*\S\+\.\%(json\)\>" contains=netrwTreeBar,@NoSpell ]]
vim.cmd [[ syn match netrwMyCustomEnv "\.env\>" contains=netrwTreeBar,@NoSpell ]]
vim.cmd [[ syn match netrwMyCustomGIT "\.gitignore\>" contains=netrwTreeBar,@NoSpell ]]

vim.cmd [[ hi netrwMyCustomJS guifg=Yellow ]]
vim.cmd [[ hi netrwMyCustomPHP guifg=LightBlue ]]
vim.cmd [[ hi netrwMyCustomTS guifg=LightBlue ]]
vim.cmd [[ hi netrwMyCustomJSON guifg=Yellow ]]
vim.cmd [[ hi netrwMyCustomEnv  guifg=Gray ]]
vim.cmd [[ hi netrwMyCustomGIT  guifg=Gray ]]

-- vim.cmd [[ hi netrwCompress term=NONE cterm=NONE gui=NONE ctermfg=10 guifg=green  ctermbg=0 guibg=black ]]
-- vim.cmd [[ hi netrwData	  term=NONE cterm=NONE gui=NONE ctermfg=9 guifg=blue ctermbg=0 guibg=black ]]
-- vim.cmd [[ hi netrwHdr	  term=NONE cterm=NONE,italic gui=NONE guifg=SeaGreen1 ]]
-- vim.cmd [[ hi netrwLex	  term=NONE cterm=NONE,italic gui=NONE guifg=SeaGreen1 ]]
-- vim.cmd [[ hi netrwYacc	  term=NONE cterm=NONE,italic gui=NONE guifg=SeaGreen1 ]]
-- vim.cmd [[ hi netrwLib	  term=NONE cterm=NONE gui=NONE ctermfg=14 guifg=yellow ]]
-- vim.cmd [[ hi netrwObj	  term=NONE cterm=NONE gui=NONE ctermfg=12 guifg=red ]]
-- vim.cmd [[ hi netrwTilde	  term=NONE cterm=NONE gui=NONE ctermfg=12 guifg=red ]]
-- vim.cmd [[ hi netrwTmp	  term=NONE cterm=NONE gui=NONE ctermfg=12 guifg=red ]]
-- vim.cmd [[ hi netrwTags	  term=NONE cterm=NONE gui=NONE ctermfg=12 guifg=red ]]
-- vim.cmd [[ hi netrwDoc	  term=NONE cterm=NONE gui=NONE ctermfg=220 ctermbg=27 guifg=yellow2 guibg=Blue3 ]]
-- vim.cmd [[ hi netrwSymLink  term=NONE cterm=NONE gui=NONE ctermfg=220 ctermbg=27 guifg=grey60 ]]
